services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
      target: dev
    container_name: tcinema-backend
    image: tcinema-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app:Z
      - backend:/app/node_modules
    # command: npm run dev
    restart: unless-stopped
    networks:
      - cinema-net
      - app-net
    depends_on:
      - mysql
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
      target: dev
    container_name: tcinema-frontend
    image: tcinema-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # fix hot reload trong Docker (Linux)
    volumes:
      - ./frontend:/app:Z
      - frontend:/app/node_modules
    command: npm run dev
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      - mysql
      - mongo

  # user-service:
  #   build:
  #     context: ./service/user-service
  #     dockerfile: Dockerfile
  #     target: dev
  #   image: vnvzio7/tcinema-user-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./service/user-service:/app
  #     - user-service:/app/node_modules
  #   networks:
  #     - cinema-net
  #   depends_on:
  #     - mysql
  #   restart: unless-stopped

volumes:
  backend:
  frontend:
  # user-service:

networks:
  app-net:
    driver: bridge
