services:
  backend:
    image: vnvzio7/tcinema-backend:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: vnvzio7/tcinema-frontend:latest  
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always  
    
  