name: SSH Hello

on:
  push:
    branches:
      - main

jobs:
  ssh-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls ~/.ssh/
          which ssh-keyscan
          ssh-keyscan -p 1808 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run command on remote server
        run: |
          ssh -p 1808 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "Hello from remote server 👋"'
