name: Build and Push Docker Image

on:
  push:
    branches: ["main", "dev"]
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USER }}" --password-stdin

      - name: Build services with Docker Compose
        run: |
          docker compose -f docker-compose.yml -f docker-compose.dev.yml build

      - name: Push images to Docker Hub
        run: |
          docker push $DOCKER_USER/tcinema-backend:latest
          docker push $DOCKER_USER/tcinema-frontend:latest
