name: Deploy to Server

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 1808 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: build and push image
        run: |
          ssh -o StrictHostKeyChecking=no -p 1808 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 
          if [ "$GITHUB_REF_NAME" = "dev" ]; then
            echo "hello dev"
          else
            echo "hello main"
          fi
